[package]
name = "oxide"
version = "0.6.0"
authors = ["tuqqu <artkurbidaev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
